plugins {
    id 'com.gradleup.shadow' version '9.0.0-rc2'
}

group = 'me.verschuls.tren'

repositories {
    maven {url "https://repo.extendedclip.com/releases/" }
}

dependencies {
    // Configuration
    implementation("com.github.verschuls:YamlFlow:v1.2.4")
    compileOnly("org.snakeyaml:snakeyaml-engine:2.7")
    // Data
    compileOnly("io.lettuce:lettuce-core:7.0.0.RELEASE")
    compileOnly("com.h2database:h2:2.4.240")
    compileOnly("org.lz4:lz4-java:1.8.0")
    // Minecraft
    compileOnly("me.clip:placeholderapi:2.11.7")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7")
    // Project
    implementation project(':api')
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('paper-plugin.yml') {
        expand props
    }
}

shadowJar {
    archiveClassifier.set('')

    archiveFileName.set("${rootProject.name}-${version}.jar")

    def prefix = project.group+".libs"
    ["de.exlll.configlib", "me.verschuls.ylf"]
            .forEach { pack ->
                def split = pack.split("\\.");
                def name = split[split.length-1];
                relocate(pack, "$prefix.$name")
            }

    exclude(
            "module-info.class",
            "META-INF/*.RSA",
            "META-INF/*.DSA",
            "META-INF/*.SF",
            "META-INF/LICENSE*",
            "META-INF/NOTICE*",
            "META-INF/DEPENDENCIES",
            "META-INF/maven/**",
            "javax/**",
            "LICENSE*",
            "AUTHORS*",
            "README*",
            "*.html",
            //"*.txt",
            "org/snakeyaml/**",
            "org/yaml/**"
    )
    dependencies {
        exclude(dependency('org.jetbrains:annotations'))
    }
    mergeServiceFiles()
    minimize()
}

jar {
    enabled = false
}

build {
    dependsOn shadowJar
}
